talav_user:
    resources:
        user:
            classes:
                model: Prony\Entity\User
        user_oauth:
            classes:
                model: Prony\Entity\UserOAuth
    email:
        from:
            email: test@test.com
            name: Tester
    registration:
        form:
            type: Prony\Form\Type\RegistrationType
            model: Prony\Form\Model\RegistrationModel
    success:
        route: prony_site_front_workspace_list

auto_mapper_plus:
    options:
        create_unregistered_mappings: true